# -*- coding: utf-8 -*-
"""MODULO6_MTCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yRoQS7oA2-ANfLbnbi2HH5yGydKZAQv
"""

!pip install mtcnn
from mtcnn import MTCNN
import cv2
from google.colab.patches import cv2_imshow

# Inicializar o detector MTCNN
detector = MTCNN()

# Carregar imagem
img = cv2.imread('./imagem_teste.jpg')

# Detectar rostos
faces = detector.detect_faces(img)

# Desenhar caixas delimitadoras
for face in faces:
    x, y, w, h = face['box']
    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

# Exibir imagem
print('Rostos detectados')
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()