# -*- coding: utf-8 -*-
"""MODULO6_OPENCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cr8CfZXYR6T7LSgQvd9TXHPcqxRZUEL1
"""

import cv2
from google.colab.patches import cv2_imshow

# Carregar o classificador Haar Cascade
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Carregar imagem
img = cv2.imread('./imagem_teste.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detectar rostos
faces = face_cascade.detectMultiScale(gray, 1.1, 4)

# Desenhar as caixas delimitadoras
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# Exibir imagem
print("Rostos detectados")
cv2_imshow(img)
# Salvar a imagem no disco
cv2.imwrite("./resultado.jpg", img)
cv2.waitKey(0)
cv2.destroyAllWindows()